# Site settings
title: Trina is Artsy
email: "trinaisartsy@gmail.com"
description: ""
url: "https://trina.coffee"
baseurl: ""
facebook_username: "trinaisartsy"
twitter_username: "trina_is_artsy"
instagram_username: "trinaisartsy"
# github_username:  "trinaisartsy"
# deviantart_username: "trinaisartsy"
flickr_username: "trinaisartsyfartsy"
discus_shortname: "trinalyn"
paypal: "ER3YV7DCSRWZU"
share: true
excerpt_separator: "<!--more-->"
header-img: art/the_usual_suspects__by_space_monkey.jpg


collections:
  art:
    output: true


# Owner/author information
owner:
  name:   Trina
  avatar: avatar.png
  favicon: favicon.ico
  info: Arts, crafts, and posts, oh my!

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : "trinalyn"

# Internal nav
nav:
  - GALLERY: "/art/"  
  - BLOG: "/blog/"
  - TUTORIALS: "/tutorials/"
  - SERVICES: "/services/"
  - ABOUT: "/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 80


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
categories_path: "/blog/category/"
tags_path: "/blog/tag/"
plugins: 
    - jekyll-paginate-v2
    - jekyll/tagging


exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Pagination
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  sort_reverse: true
  per_page: 3
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)

# tags
tag_page_layout: tag_page
tag_page_dir: tag

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

prose:
  rooturl: '_posts/'
  siteurl: 'https://trina.coffee'
 # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
